version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./start.sh:/start.sh:ro
    entrypoint: ["/bin/bash", "/start.sh"]
volumes:
  ollama-data:
